<?php

namespace ContainerMsGxYxQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemathiquesInputTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\ThemathiquesInputType' shared autowired service.
     *
     * @return \App\Form\Type\ThemathiquesInputType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/ThemathiquesInputType.php';

        return $container->privates['App\\Form\\Type\\ThemathiquesInputType'] = new \App\Form\Type\ThemathiquesInputType(($container->privates['App\\Repository\\ThematiquesRepository'] ?? $container->load('getThematiquesRepositoryService')));
    }
}
