<?php

namespace ContainerOxcLJW6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAvocatsInputTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\AvocatsInputType' shared autowired service.
     *
     * @return \App\Form\Type\AvocatsInputType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/AvocatsInputType.php';

        return $container->privates['App\\Form\\Type\\AvocatsInputType'] = new \App\Form\Type\AvocatsInputType(($container->privates['App\\Repository\\AvocatsRepository'] ?? $container->load('getAvocatsRepositoryService')));
    }
}
