<?php

namespace ContainerOxcLJW6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormationTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\FormationType' shared autowired service.
     *
     * @return \App\Form\Type\FormationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/FormationType.php';

        return $container->privates['App\\Form\\Type\\FormationType'] = new \App\Form\Type\FormationType();
    }
}
