<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMsGxYxQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMsGxYxQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMsGxYxQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMsGxYxQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMsGxYxQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'MsGxYxQ',
    'container.build_id' => '5dbe2210',
    'container.build_time' => 1655992348,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMsGxYxQ');
