<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_internals_add-to-unscopables_js-node_modules_core-js_internals_a-13a0cb.js',
                '/build/vendors-node_modules_core-js_internals_a-constructor_js-node_modules_core-js_modules_es_funct-7ca68b.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_bootstrap_dist_js_boo-0f6d49.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
        'formation' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/formation.js',
            ],
        ],
        'script' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_internals_add-to-unscopables_js-node_modules_core-js_internals_a-13a0cb.js',
                '/build/script.js',
            ],
        ],
        'calendarJs' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_core-js_internals_add-to-unscopables_js-node_modules_core-js_internals_a-13a0cb.js',
                '/build/vendors-node_modules_core-js_internals_a-constructor_js-node_modules_core-js_modules_es_funct-7ca68b.js',
                '/build/vendors-node_modules_core-js_modules_es_array_concat_js-node_modules_core-js_modules_es_array-489df4.js',
                '/build/calendarJs.js',
            ],
        ],
        'calendar' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/calendar.css',
            ],
        ],
    ],
],

]];
